name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Run tests
      run: |
        # Install xvfb for headless VS Code testing
        sudo apt-get update
        sudo apt-get install -y xvfb
        
        # Set test environment variables
        export CI=true
        export NODE_ENV=test
        export DISPLAY=:99.0
        
        # Start virtual display
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
        # Run tests with the CI-aware test runner
        npm run test:integration
      env:
        DISPLAY: ':99.0'
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Package extension
      run: |
        npm install -g vsce
        vsce package
        
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: speechify-extension
        path: '*.vsix'
        
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Check for sensitive files
      run: |
        # Check for accidentally committed sensitive files (only in Git index)
        if git ls-files | grep -E "(test-config\.json|.*\.key|.*\.secret)$"; then
          echo "Error: Sensitive files found in Git repository"
          echo "These files should not be committed:"
          git ls-files | grep -E "(test-config\.json|.*\.key|.*\.secret)$"
          exit 1
        fi
        
        # Check for hardcoded secrets in committed files
        if git grep -E "(subscriptionKey|api[_-]?key).*['\"].*[0-9a-f]{32}" -- "*.ts" "*.js" "*.json"; then
          echo "Error: Potential hardcoded secrets found in committed files"
          exit 1
        fi
        
        echo "✅ No sensitive files or hardcoded secrets found in repository"
